#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it on the PATH, you may need to set the SHELL variable to wherever
#       the POSIX shell is located.
#
#   (2) The splitting of words into multiple lines is a workaround for
#       certain shells' inability to handle strings containing spaces. The workaround
#       exploits the fact that "$0" in most shells means the program name and "-a"
#       means "all".
#
#       WHERE FOR HELP SEE HTTPS://PUBS.OPENGROUP.ORG/ONLINEPUBS/9699919799/UTILITIES/ECHO.HTML
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a softlink
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    PRG=`readlink "$PRG"`
done
PRG_DIR=`dirname "$PRG"`
APP_HOME=`cd "$PRG_DIR" && pwd -P` || exit 1

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn ( ) {
    echo "$*" >&2
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
if [ -z "$OSTYPE" ]; then
    ostype=`uname -s`
    OSTYPE=$ostype
fi
cygwin=false
msys=false
dwin=false
native=false
case "$OSTYPE" in
  CYGWIN* )
    cygwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  CYGWIN_NT-* )
    cygwin=true
    ;;
  UWIN* )
    die "UWIN environment is not supported with Gradle."
    ;;
  Darwin* )
    native=true
    ;;
 esac

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = true ] || [ "$msys" = true ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 3 -type d -name java_modules 2>/dev/null || true`
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGPATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" 2>/dev/null` || true
        CHECK2=`echo "$arg"|egrep -c "^-"`    # number of args
        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                 ### Added a condition
            eval `echo args$i`=`cygpath --path --unix "$arg"`
        else
            eval `echo args$i`="\"$arg\""
        fi
        i=$(( $i + 1 ))
    done
    case $i in
        0) set -- ;;
        1) set -- "$args0" ;;
        2) set -- "$args0" "$args1" ;;
        3) set -- "$args0" "$args1" "$args2" ;;
        4) set -- "$args0" "$args1" "$args2" "$args3" ;;
        5) set -- "$args0" "$args1" "$args2" "$args3" "$args4" ;;
        6) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" ;;
        7) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" ;;
        8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
        9) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" "$args8" ;;
    esac
fi

# Escape application args
save ( ) {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'" ; done
    echo " "
}
APP_ARGS=`save "$@"`

# Collect all arguments for the java command, stacking in reverse order
cmd=""
for arg in "$@" ; do
    cmd="\"$arg\" $cmd"
done

# By default we should be in the correct project dir, but when run from Gradle itself
# we need to use the fully qualified name.
if [ -z "$GRADLE_MAIN_CLASS" ] ; then
    GRADLE_MAIN_CLASS="org.gradle.wrapper.GradleWrapperMain"
fi

# Disallow running Gradle as root
if [ "$(id -u)" = "0" ] ; then
    die "Running Gradle as root is not supported. Please run Gradle as a non-root user."
fi

# Determine the Java command to use in order to execute the application.
find_java_exec ( ) {
    if [ -z "$JAVA_HOME" ] ; then
        javaExecutable="`which java`"
        [ -z "$javaExecutable" ] && die "JAVA_HOME is not set and no 'java' command could be found in your PATH."
    else
        javaExecutable="$JAVA_HOME/bin/java"
        [ ! -e "$javaExecutable" ] && die "JAVA_HOME points to a non-existent java home folder $JAVA_HOME and no 'java' command could be found in your PATH."
    fi
    if [ ! -x "$javaExecutable" ] ; then
        die "The java command '$javaExecutable' is not executable."
    fi
    echo "$javaExecutable"
}

JAVA_EXEC="$(find_java_exec)"

if [ ! -d "$APP_HOME/gradle/wrapper" ] && [ -e "$APP_HOME/gradlew" ] ; then
    # When used by Gradle/enlight, the generated gradlew assumes it is in a subdirectory
    APP_HOME="`dirname "$APP_HOME"`"
fi

exec "$JAVA_EXEC" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    $GRADLE_MAIN_CLASS \
    "$@"
